spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/springbootangular
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false
logging:
  level:
    org:
      flywaydb: debug

jwt:
  secret: ${JWT_SECRET:TEWXjbnfaHMB2qt3jTRQ5szUssa91McOmandPp4djGses2nhgBIsNqYD7A0iX8n}

server:
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

admin:
  password: ${ADMIN_PASSWORD:password}
  email: ${ADMIN_EMAIL:admin@test.com}

app:
  url: ${APP_URL:http://localhost:4200}

validation:
  user:
    username:
      max-length: 20
      min-length: 4
    name:
      max-length: 255